# Generated by Django 5.0.6 on 2024-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='course')),
                ('description', models.TextField(max_length=200, unique=True)),
                ('ageLimit', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
