# Generated by Django 5.0.6 on 2024-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_testimonialmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='gallery')),
            ],
        ),
    ]
