# Generated by Django 5.0.6 on 2024-05-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('course', '0003_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcatagory'),
            preserve_default=False,
        ),
    ]
