# Generated by Django 5.0.6 on 2024-05-20 08:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
